#pragma once
// generated code, do not edit
// generated by 'python calibration/process.py'
// clang-format off

#include "stdbool.h"
#include "string.h" // memset

#define CALIBRATION_NUM_TRAINS 6
#define CALIBRATION_MAX_TRAIN 79

struct speed_level_t {
  bool measured;
  int expected_velocity_mmps;
};

struct train_data_t {
  int train;
  struct speed_level_t speeds[15];
};

struct calibration_data_t {
  struct train_data_t trains[CALIBRATION_NUM_TRAINS];
  int index_of_train[CALIBRATION_MAX_TRAIN + 1];
};

void fill_calibration_data(struct calibration_data_t* c);

